version: "3.9"
services:
 mongodb:
    image: mongo:6.0.9
    container_name: mongodb
    ports:
      - "27010:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    networks:
      - bss_dev
volumes:
  mongodb-data:
    driver: local
networks:
  bss_dev:
    driver: bridge