# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "<SHOPIFY_API_KEY>"
name = "<APP_NAME>"
handle = "<APP_HANDLE>"
application_url = "https://dev-bloy-<n>.<CF_ZONE_NAME>"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "<STOREFRONT_SHOPIFY_DOMAIN>"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_files,write_files,read_orders,read_customers,write_customers,read_products,read_themes,write_discounts,read_metaobject_definitions,read_metaobjects,write_metaobject_definitions,write_metaobjects,write_store_credit_account_transactions,read_store_credit_accounts"
optional_scopes = ["write_orders"]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dev-bloy-<n>.<CF_ZONE_NAME>/auth/callback",
  "https://dev-bloy-<n>.<CF_ZONE_NAME>/auth/shopify/callback",
  "https://dev-bloy-<n>.<CF_ZONE_NAME>/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
